project:
  type: book
  output-dir: docs

book:
  title: "NLPR"
  author: "Zane Dax (She/They)"
  date: "2022-09-12"
  chapters:
    - index.qmd # preface
    - preface.qmd # 1
    - Quanteda-corpus.qmd
    - TidyText.qmd
    - summary.qmd
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: [darkly, custom.scss]
    cover-image: bookcover.png
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: bookcover.png



