project:
  type: book

book:
  title: "NLPR"
  author: "Zane Dax (She/They)"
  date: "2022-09-12"
  chapters:
    - index.qmd # preface
    - preface.qmd # 1
    - Quanteda-corpus.qmd
    - TidyText.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: slate
    cover-image: cover.png
  pdf:
    documentclass: scrreprt
  epub: 
    cover-image: cover.png



